name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}